// Shared light theme used across the app so screens stay visually consistent.
export const appTheme = {
  colors: {
    background: '#f7f6f2',
    backgroundAlt: '#f0f3ef',
    surface: '#ffffff',
    surfaceMuted: '#f8faf9',
    surfaceSoft: '#eef6f3',
    surfaceSoftAlt: '#e7edea',
    surfaceTint: '#f4f4f4',
    border: '#dddddd',
    borderSoft: '#d9d9d9',
    borderSubtle: '#dfe7e3',
    text: '#171717',
    textStrong: '#17202a',
    textMuted: '#666666',
    textSoft: '#555555',
    textSubtle: '#777777',
    primary: '#1f6f5f',
    primaryPressed: '#19594d',
    primarySoft: '#e6f0ec',
    accent: '#f28a54',
    successBg: '#e4f6ee',
    successBorder: '#b9e7d2',
    successText: '#1f6f5f',
    dangerBg: '#fdeaea',
    dangerBorder: '#f4caca',
    dangerText: '#a33b3b',
    dangerTextStrong: '#b91c1c',
    white: '#ffffff',
  },
} as const;
